# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e59240ab03688f4b12a2a47d1a4cdc484f4b65526fd10ddb31b24ba73a0cbca3db29688cf9956cecb173db2d0c30a2002609d38b390ed60ac8621d7c1f2c5775

test:
  secret_key_base: e11cb85b166ad214a2c6c8d2d73da44c03934abaa2da5484e9f410e4790a324d6af20aa026e0ab8c5fa284cbd0da8fe8383b3f6ed7e2931f6d9adc6df9800423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
